INREL-3969 Finalize Lexicon
BurdaMagazinOrg/infinite-theme pull request #128
Opened 2018-06-11 17:04 UTC by danschalow

## [INREL-3969](https://jira.burda.com/browse/INREL-3969) 
Styled Lexicon page

## How to test:
Please provide a brief step-by-step instruction.
- https://feature1.elle.de/modelexikon

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)
- [ ] I have documented the changes (where applicable)

2018-06-14 14:02 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +        margin-top: 8px;
I think we have variables for that. Please check `_variables.base.gaps.scss`

2018-06-14 14:03 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +        @include text-helper-size($font-content, $font-size-medium, 20px);
Please also avoid magic numbers here. You should consider move that to a specific var.

2018-06-14 14:03 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +        margin-top: 6px;
Magic number =)

2018-06-14 14:03 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +        margin-top: 8px;
Same here

2018-06-14 14:03 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +          padding-bottom: 56.2%;
There should be a aspect ratio mixin for that.

2018-06-14 14:06 UTC, saviomuc requested changes
Looks good so far. Some small nitpicks and please check the templates (where are they from)

2018-06-15 12:38 UTC, danschalow commented
- Replaced all magic numbers

2018-06-15 12:58 UTC, saviomuc requested changes

2018-06-15 12:58 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +        margin-top: 6px;
Please use `$lexicon-teaser__copy--margin-top__mobile;`

2018-06-15 12:58 UTC, saviomuc commented on sass/components/lexicon/_lexicon.scss
> +          background: #e7e7e7;
Please move to vars.

2018-06-15 13:53 UTC, saviomuc approved these changes
LGTM :shipit:

2018-06-20 08:33 UTC, merged