INREL-4135 ecommerce slider lazyloading
BurdaMagazinOrg/infinite-theme pull request #131
Opened 2018-06-13 11:29 UTC by Nicozilla

## [INREL-4135](https://jira.burda.com/browse/INREL-4135) 
- Update swiper.js lib from 3.4.2 to 4.3.3
- Include/Create swiper lazy loading template
- Change ecommerce-slider styling

## How to test:
- Checkout feature/INREL-4135-ecommerce-slider-lazyloading
- Open the network tab. 
- Go to a Ecommerce-Slider-Widget and swipe/click to the next product.

Now you should see that the next / perv product image are lazyloaded.

## Checklist:

- [ x ] I have verified that the code works
- [ x ] I have verified that the code is easy to understand
- [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)
- [ ] I have documented the changes (where applicable)

2018-06-14 14:25 UTC, saviomuc commented on js/infinite/views/products/ecommerce-slider-view.js
> +        //loadPrevNext: true
Please remove comment if it's not used

2018-06-14 14:26 UTC, saviomuc commented on js/infinite/views/base/base-list-swipeable-view.js
> +            this.swiperApi = new Swiper(this.$swiperContainer[0], this.settings);
What does `$swiperContainer[0]` refer to?

2018-06-14 14:27 UTC, saviomuc commented on js/infinite/views/products/ecommerce-slider-view.js
> +      //this.swiperApi = this.$swiperContainer.swiper(this.settings);
Please remove comment

2018-06-14 14:27 UTC, saviomuc commented on js/infinite/views/base/base-list-swipeable-view.js
>              this.$swiperContainer = this.$el.find('.container-content');
Do we still need `swiperContainer `?

2018-06-14 14:27 UTC, saviomuc requested changes
Some questions

2018-06-18 06:11 UTC, Nicozilla commented on js/infinite/views/products/ecommerce-slider-view.js
> +        //loadPrevNext: true
Sorry. Done.

2018-06-18 06:12 UTC, Nicozilla commented on js/infinite/views/base/base-list-swipeable-view.js
> +            this.swiperApi = new Swiper(this.$swiperContainer[0], this.settings);
$swiperContainer[0] is the plain HTML Node. 
swiperContainer is the jQuery reference.

2018-06-18 06:12 UTC, Nicozilla commented on js/infinite/views/products/ecommerce-slider-view.js
> +      //this.swiperApi = this.$swiperContainer.swiper(this.settings);
Done.

2018-06-18 06:13 UTC, Nicozilla commented on js/infinite/views/base/base-list-swipeable-view.js
>              this.$swiperContainer = this.$el.find('.container-content');
$swiperContainer is the saved jQuery reference. We are using jQuery so I think it's ok.

2018-06-18 15:27 UTC, saviomuc commented
LGTM :shipit:

2018-06-20 14:57 UTC, merged