INREL-3764 new article trigger
BurdaMagazinOrg/infinite-theme pull request #134
Opened 2018-06-18 08:34 UTC by Nicozilla

## [INREL-3764](https://jira.burda.com/browse/INREL-3764) 
- new article_footer_blocks_common in common template. So we can add dynamically the next-article-info-layer for specific platform (InStyle next article scroll logic when you see the preloader

## How to test:
Scroll fast to the next article. Now you see the preloader. After the preloading is done it's scrolling automatically to the next article.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)
- [ ] I have documented the changes (where applicable)

2018-06-19 13:30 UTC, saviomuc commented on js/infinite/libs/shortcuts/infinite_custom.js
> +    this.options.onAfterPrePageLoad($items);
1. What is the purpose of this line?

2. Naming: `onAfterPrePageLoad` sounds confusing to me. Further down it is a reference to `onAfterPrePageLoad: _.bind(this.onAfterPreLoad, this),`. I think we should have consistent names to make it as easy as possible to understand.

2. Usage: Can you also clarify when the event triggers?

2018-06-19 13:31 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +    naviHeight: 56,
This is a magic number. Where does 56 come from? Is there a reason it has to be in base-feed-view. If it's mapped to the height of the navigation element how can we make it reusable across all other pages?

2018-06-19 13:33 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      this.naviHeight = document.querySelector('#menu-main-navigation').offsetHeight || this.naviHeight;
In that case wouldn't it make more sense to use getElementByID? Also I am not sure if using an ID is a good idea. The ID could potentially change (in template and CSS). A solution which is a little bit more stable would be a class with some sort of prefix like `js-main-menu-navigation`

2018-06-19 13:33 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +        onAfterPrePageLoad: _.bind(this.onAfterPreLoad, this),
See comment above at https://github.com/BurdaMagazinOrg/infinite-theme/pull/134/files#diff-ba53da8dd514fd24e59094b00fe41f91R89

2018-06-19 13:34 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      /**
Please use single line comments if the comment is on one line.

2018-06-19 13:36 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      if (((window.scrollY + window.innerHeight) === document.body.clientHeight) && $('body').hasClass('page-article')) {
Can we use something more descriptive? Like `var atBottomOfPage = (window.scrollY + window.innerHeight) === document.body.clientHeight`

2018-06-19 13:37 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      if (((window.scrollY + window.innerHeight) === document.body.clientHeight) && $('body').hasClass('page-article')) {
Also not sure why we need the condition `$('body').hasClass('page-article')`. I think you are mixing two different contexts here (scroll position and execution scope). execution scope should be handled somewhere.

2018-06-19 13:38 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +        this.scrollToAppendedElement = true;
Can we use the model here and use `listenTo`? Or is there a reason not to use it?

2018-06-19 13:38 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
>        //console.log("loading done", " View >> ", this.id || this.$el.attr('id') || this.$el.attr('class'));
Please remove unused line

2018-06-19 13:39 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      var tmpElement = pItem[0];
What is the meaning of `tmpElement`? What does it contain? What is the meaning of `pItem`? Can we use more specific variable names?

2018-06-19 13:40 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +      this.parseInfiniteView($(tmpElement), {modelList: this.model, initialDOMItem: false}); //delegateElements: true,
Please remove comment at end

2018-06-19 13:40 UTC, saviomuc requested changes
Code seems to work. Nitpicks / Questions regarding naming and structure.

2018-06-19 14:07 UTC, saviomuc requested changes
Questions regarding code usage, structure, naming and scope.
Needs rework regarding naming, unused code and structure.

2018-06-19 15:52 UTC, Nicozilla commented on js/infinite/libs/shortcuts/infinite_custom.js
> +    this.options.onAfterPrePageLoad($items);
removed - not necessary

2018-06-19 15:53 UTC, Nicozilla commented on js/infinite/views/base/base-feed-view.js
> +      this.naviHeight = document.querySelector('#menu-main-navigation').offsetHeight || this.naviHeight;
getElementByID -> good idea

2018-06-19 15:53 UTC, Nicozilla commented on js/infinite/views/base/base-feed-view.js
> +    naviHeight: 56,
we set it already dynamically

2018-06-19 15:57 UTC, Nicozilla commented on js/infinite/views/base/base-feed-view.js
> +      if (((window.scrollY + window.innerHeight) === document.body.clientHeight) && $('body').hasClass('page-article')) {
It should only be scrolled on articles.

2018-06-19 16:00 UTC, Nicozilla commented on js/infinite/views/base/base-feed-view.js
> +      var tmpElement = pItem[0];
Changed. Get jQueryElement -> $appendedElement
```javascript 
      onAfterPageLoad: function ($appendedElement) {
      var appendedElement = $appendedElement[0];
```

2018-06-19 16:02 UTC, Nicozilla commented on js/infinite/views/base/base-feed-view.js
> +        this.scrollToAppendedElement = true;
On this time and position not practicable. We want the check before the content is appended. When the content is appended and the flag is true - scroll to next article.

2018-06-21 11:05 UTC, saviomuc commented on js/infinite/views/base/base-feed-view.js
> +        this.atBottomOfPage = true;
Just a note, you could also do:

`this.atBottomOfPage = ((window.scrollY + window.innerHeight) === document.body.clientHeight)`

As the assignment key (atBottomOfPage) is already clear here.

2018-06-21 11:05 UTC, saviomuc approved these changes
One note.

LGTM :shipit:

2018-06-22 13:47 UTC, merged