Refactoring - Bootstrap, Bower, Gulp
BurdaMagazinOrg/infinite-theme pull request #41
Opened 2017-02-14 14:04 UTC by landsman

Hi Thunder team!
As I was promised here is refactored theme.

**Change log:**
Removed bootstrap folder - bower,
Removed JS libs -> bower,
Created package.json with npm libs and gulp default task init after install,
Removed compass -> gulp,
Fixed waypoint lib stuff with wrapper inline height (new version feature),
Removed ionicons -> bower,
Updated .gitignore,
Removed css file -> it will be compiled by "npm install" fired from composer - see: https://github.com/BurdaMagazinOrg/thunder-project/pull/7

I tested these changes on my environment and it looks fine.
Please give me a feedback :-)

2017-02-14 14:22 UTC, dbosen commented
Wow, lots of changes, this needs a while :)

2017-02-14 14:42 UTC, landsman commented
Sure, I look forward to answers.
I think that npm based deployment of themes will be cool.
In future we can do all only by `composer update` if this we have in thunder: https://github.com/BurdaMagazinOrg/thunder-project/pull/8

2017-02-14 15:11 UTC, tjwelde requested changes
Thanks for your contribution.
The npm/bower/gulp workflow has admittedly more components as the sass/compass one, but it is nice to load the needed libraries via a package management.
For now I would keep it, but we will maybe change to a https://asset-packagist.org/ workflow, which integrates with composer more nicely.
Some things still need to be resolved. I added feedback to the code here.

2017-02-14 15:11 UTC, tjwelde commented on sass/_reset.scss
> +// reset from compass i think
The original reset code can be found in mixin: "global-reset" here: https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/reset/_utilities.scss

2017-02-14 15:11 UTC, tjwelde commented on Gulpfile.js
> +var domain_bs	= 'http://thunder.dev:8888'; // @todo: think about better solution
We could set these in commandline, or have a seperate settings file.

2017-02-14 15:11 UTC, tjwelde commented on Gulpfile.js
> +var port_bs		= 8888; // @todo: think about better solution
this seems to be redundant

2017-02-14 15:11 UTC, tjwelde commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
Why is that needed here?

2017-02-14 15:11 UTC, tjwelde commented on sass/mixins/_mixins.compass.scss
> +  //@include transform($trans, $only3d); todo!
Without that, the mixin does nothing.
The transform mixin seems to be used, to prefix it. See: [github.com/Compass/compass/css3/_transform.scss#L141](https://github.com/Compass/compass/blob/4de01475c98449c4435359544db443fd3da6e9d3/core/stylesheets/compass/css3/_transform.scss#L141)
Since this PR uses autoprefixer, there is no need for that and you can just add the transform property here.

2017-02-14 15:11 UTC, goldquest commented on sass/mixins/_mixins.contents.scss
> +      @include make-xs-column(10);
Why is that necessary?

2017-02-14 15:13 UTC, landsman commented on sass/mixins/_mixins.contents.scss
> +      @include make-xs-column(10);
Because new version of bootstrap don't know this mixin name. I think that it was renamed.

2017-02-14 15:15 UTC, landsman commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
Because new version of Waypoints removed parent height inline style condition - more is here: https://github.com/imakewebthings/waypoints/pull/553 but this is solved our problem with this.

2017-02-14 15:16 UTC, goldquest commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
You added the old variable here: https://github.com/BurdaMagazinOrg/infinite-theme/pull/41/files#diff-5e31b7def87086acda09cefdee13e38eR429 but are not using it at this line. Why?

2017-02-14 15:17 UTC, landsman commented on Gulpfile.js
> +var port_bs		= 8888; // @todo: think about better solution
I know, but its only for develop environment - BrowserSync.
I don't know how set domain, port via bash parameter or etc.

2017-02-14 15:18 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
It's old variable, in old bootstrap version I think.
I can remove this: https://github.com/BurdaMagazinOrg/infinite-theme/pull/41/files#diff-5e31b7def87086acda09cefdee13e38eR429.

2017-02-14 15:19 UTC, landsman commented on Gulpfile.js
> +var domain_bs	= 'http://thunder.dev:8888'; // @todo: think about better solution
It should be great! How?

2017-02-14 15:20 UTC, landsman commented on sass/_reset.scss
> +// reset from compass i think
Yea, but It depends on next compass mixins what we don't want :-(

2017-02-14 15:23 UTC, landsman commented on sass/mixins/_mixins.compass.scss
> +  //@include transform($trans, $only3d); todo!
Right, autoprefixer can be solved this.
I'll change it.

2017-02-14 15:26 UTC, goldquest commented on Gulpfile.js
> +var domain_bs	= 'http://thunder.dev:8888'; // @todo: think about better solution
You could use this tool: https://github.com/gulpjs/gulp-util. It uses minimist to get the commandline arguments.
Also have a look here: http://stackoverflow.com/questions/23023650/is-it-possible-to-pass-a-flag-to-gulp-to-have-it-run-tasks-in-different-ways.

2017-02-14 20:08 UTC, landsman commented
I was send update :)

2017-02-15 09:24 UTC, landsman commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
Is it right for now?

2017-02-15 09:25 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Fixed

2017-02-15 11:25 UTC, goldquest commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
I'll have to test it.

2017-02-15 11:29 UTC, goldquest commented on sass/components/_breadcrumb.scss
> +    display: inline-block;
Here you didn't include the vertical-align statement, of the inline-block mixin. Is it not needed anymore?

2017-02-15 11:29 UTC, goldquest commented on sass/mixins/_mixins.lists.scss
> -    color: inherit;
why is that removed?

2017-02-15 11:30 UTC, goldquest commented on sass/mixins/_mixins.menus.scss
> +    vertical-align: middle;
here the display:inline-block is missing, or?

2017-02-15 11:38 UTC, goldquest commented on sass/_reset.scss
> +// reset from compass i think
Just make a temp folder and place a test.scss file in the sass subdirectory.
In this file just write `@import "compass/reset";` and do a `compass compile`. Then copy/paste.

2017-02-15 12:04 UTC, landsman commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
Here is a video about this problem, what I fixed: https://youtu.be/RIjO-tw4z2A

2017-02-15 12:06 UTC, landsman commented on sass/components/_breadcrumb.scss
> +    display: inline-block;
Yea, Its better without.

2017-02-15 12:08 UTC, landsman commented on sass/mixins/_mixins.menus.scss
> +    vertical-align: middle;
Botto was `display: none` and It not making sense.
See: https://github.com/BurdaPraha/infinite-theme/blob/fc2d6b638feea874556c4d9c1bb4a50269dce9f5/sass/mixins/_mixins.menus.scss#L115

2017-02-15 12:09 UTC, landsman commented on sass/mixins/_mixins.lists.scss
> -    color: inherit;
Because color was bottom yet:
https://github.com/BurdaPraha/infinite-theme/blob/fc2d6b638feea874556c4d9c1bb4a50269dce9f5/sass/mixins/_mixins.lists.scss#L87

2017-02-15 12:16 UTC, landsman commented on sass/_reset.scss
> +// reset from compass i think
Done

2017-02-15 12:21 UTC, goldquest commented on sass/mixins/_mixins.menus.scss
> +    vertical-align: middle;
hmm, ok.

2017-02-15 12:22 UTC, goldquest commented on sass/mixins/_mixins.lists.scss
> -    color: inherit;
ok

2017-02-15 12:23 UTC, goldquest commented on sass/components/_breadcrumb.scss
> +    display: inline-block;
ah, thanks

2017-02-15 12:27 UTC, landsman commented
Here you can see created README: https://github.com/BurdaPraha/infinite-theme/tree/refactoring-bootstrap

Do you think thats ok?

2017-02-15 12:32 UTC, goldquest commented
Yes, that is very good and important. I will just clean up the language a little bit ;)

2017-02-15 12:34 UTC, landsman commented
LICENCE file should be good too I think.

2017-02-16 09:56 UTC, tjwelde requested changes

2017-02-16 09:56 UTC, goldquest commented on Gulpfile.js
> +    if(process.argv[3] || process.argv[4] === '--' + environments[0])
The first part here only checks, if there is a fourth argument present, not if it is actually `--dev`. Only the second part does that.

2017-02-16 09:56 UTC, goldquest commented on Gulpfile.js
> +    environments    = ['dev', 'stage', 'prod'];
Why do we have different environment options, if we only use dev? Do you plan on using the other?

2017-02-16 10:02 UTC, landsman commented on Gulpfile.js
> +    environments    = ['dev', 'stage', 'prod'];
Yeah, I think that these 3 types of environment should be defined and can be used in future. Do you disagree?

2017-02-16 10:03 UTC, landsman commented on Gulpfile.js
> +    if(process.argv[3] || process.argv[4] === '--' + environments[0])
It works for me. You can use: 
1. gulp sass --dev
2. gulp watch --dev

2017-02-16 10:07 UTC, landsman commented on Gulpfile.js
> +    if(process.argv[3] || process.argv[4] === '--' + environments[0])
Maybe `gulp watch` should change environment to `dev` by default, what you think?

2017-02-16 10:39 UTC, goldquest commented on Gulpfile.js
> +    if(process.argv[3] || process.argv[4] === '--' + environments[0])
It works, but it also works with any other argument. E.g. with `gulp sass --prod`.

2017-02-16 10:41 UTC, goldquest commented on Gulpfile.js
> +    if(process.argv[3] || process.argv[4] === '--' + environments[0])
Yes, `gulp watch` can have dev as default

2017-02-16 10:44 UTC, goldquest commented on Gulpfile.js
> +    environments    = ['dev', 'stage', 'prod'];
I think, we should add environments, as we need them. Also prod is the default and staging should normally have everything compiled like what it would be on a prod env.

2017-02-16 10:45 UTC, landsman commented on Gulpfile.js
> +    environments    = ['dev', 'stage', 'prod'];
OK, I'll remove it.

2017-02-16 10:50 UTC, goldquest commented on js/infinite/views/sticky-view.js
> +            this.$el.parent().attr('style', '');
Approved

2017-02-16 13:28 UTC, goldquest commented on sass/mixins/_mixins.contents.scss
> +      @include make-xs-column(10);
Yes, it seems like it was renamed.

2017-02-16 13:35 UTC, goldquest commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Yeah, but now the value is not the same as the old one, which would need to be tested. I would prefer having the old bootstrap variables as you had before, but with a todo comment, to check, if it is possible to switch to `$screen-xs-max`

2017-02-16 14:03 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Nothing old please 👎 
We can resolve all in this PR...
What different is between values?

2017-02-16 15:25 UTC, goldquest commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
`$screen-xxs-max` was `479px` and `$screen-xs-max` is `767px` now. That's quite a difference.

2017-02-16 15:27 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Its not problem, we can override this variable in https://github.com/BurdaPraha/infinite-theme/blob/refactoring-bootstrap/sass/_variables.scss#L428 do you agree?

2017-02-16 23:25 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Done

2017-02-18 18:02 UTC, landsman commented
Is there anything to solve?

2017-02-20 10:22 UTC, goldquest commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
the variable is just called `$screen-xx-max`, so it is not used

2017-02-20 12:31 UTC, landsman commented on sass/mixins/_mixins.teasers.scss
> +  @media (max-width: $screen-xs-max) {
Fixed

2017-02-20 16:18 UTC, goldquest commented on sass/_variables.scss
> +$screen-xx-max: 479px;
Here is a typo. Should be `$screen-xxs-max`

2017-02-20 16:26 UTC, landsman commented on sass/_variables.scss
> +$screen-xx-max: 479px;
fixed

2017-02-21 13:54 UTC, goldquest commented
Ok, the old used bootstrap seems to be v3.3.4. It was modified to contain the xxs and xl columns.
I think we should keep the changes in a "bootstrap_modifications" file.   

Also we should use the bower version 3.3.4 for now, we can bump it up, after this PR is merged.  

The variables you renamed should be reverted back to what they were.

2017-02-21 13:58 UTC, landsman commented
@goldquest I don't understand why we should use old deprecated `3.3.4` version again if old version of theme don't using bower, npm etc. We should change version of theme (composer) what says that here should be BC break, right?

2017-02-21 16:30 UTC, merged

2017-02-21 16:32 UTC, goldquest commented on sass/layouts/_layouts.global.scss
> +  list-style: none;
Is this a new style change?

2017-02-21 16:38 UTC, landsman commented on sass/layouts/_layouts.global.scss
> +  list-style: none;
I think that I was tried to fix admin menu and compass do same thing

2017-02-21 16:53 UTC, goldquest commented
Shit, I accidentally merged it. Can you make a new PR, please?

2017-02-21 16:55 UTC, landsman commented
@goldquest With ... removed this ol, ul style ?

2017-02-21 16:56 UTC, goldquest commented
no, just as it is right now