INREL-3358: Fixed - Link for generic products do not work for shop it
BurdaMagazinOrg/infinite-theme pull request #86
Opened 2018-01-30 14:34 UTC by alex-schell

2018-01-31 13:14 UTC, saviomuc commented on js/infinite/views/products/product-view.js
> +          if (tmpExternalTrackingURL.indexOf("//td.") > -1 && tmpLinkPosition > -1) {
Currently we lack some clarity in the code. It could be further refined by creating a variable for each of them. 

For instance:
```
var isTracdelightURL = externalTrackingURL.indexOf("//td.") > -1;
var positionOfLinkParam = externalTrackingURL.indexOf("&link");
var hasLinkParam = positionOfLinkParam > -1;
```

```
 if (isTracdelightURL && hasLinkParam) {
...
  }
```



**Keep in mind**
Variables are not local in `switch / case` constructs but always local to functions. (Hoisting!) This means you need to move them to Line 118.

2018-01-31 13:22 UTC, saviomuc reviewed
Overall code works and looks fine to me. We should however try to improve the code with each commit.

The base code is extremely smelly so it would be great if you could take some time to refactor it.

2018-01-31 13:22 UTC, saviomuc commented on js/infinite/views/products/product-view.js
Not your scope but we should always try to leave code in a better state than before (@see http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)

To improve clarity of tmpSlicedTitle we could create a variable and break down the code into multilines. I.e.:

```
var productTitle = '';
```

```
 productTitle = this.model
                .get('title')
                .replace(/[\/. ,:-]+/g, "_")
                .toLowerCase()
                .slice(
                  0,
                  Math.min(10, this.model.get('title').length)
                );
```

2018-01-31 13:22 UTC, saviomuc commented on js/infinite/views/products/product-view.js
> +            tmpExternalTrackingURL = tmpExternalTrackingURL.substr(0, tmpLinkPosition) + tmpSlicedString + tmpExternalTrackingURL.substr(tmpLinkPosition)
I don't understand the concept of tmp variable names. All variables are temporary in their execution context.
It would be great to rename all occurences of `tmpExternalTrackingURL` to `externalTrackingURL`.

2018-01-31 13:22 UTC, saviomuc commented on js/infinite/views/products/product-view.js
> +          if (tmpExternalTrackingURL.indexOf("//td.") > -1 && tmpLinkPosition > -1) {
Currently we lack some clarity in the code. It could be further refined by creating a variable for each of them. 

For instance:
```
var isTracdelightURL = externalTrackingURL.indexOf("//td.") > -1;
var positionOfLinkParam = externalTrackingURL.indexOf("&link");
var hasLinkParam = positionOfLinkParam > -1;
```

```
 if (isTracdelightURL && hasLinkParam) {
...
  }
```



**Keep in mind**
Variables are not local in `switch / case` constructs but always local to functions. (Hoisting!) This means you need to move them to Line 118.

2018-01-31 13:26 UTC, saviomuc requested changes
1) The structure should be:

```
case ProductView.PROVIDER_GENERIC:

if (isTracdelightURL && hasLinkParam) {
  // create tmpSlicedString

  if (isDrupalEntityOrNode) {
 // overwrite tmpSlicedString
}

// set externalTrackingURL
}

```

2) Please do some housekeeping and make the overall code a little bit easier on the eye (see review comments)

2018-02-01 18:18 UTC, alex-schell commented on js/infinite/views/products/product-view.js
> +          if (tmpExternalTrackingURL.indexOf("//td.") > -1 && tmpLinkPosition > -1) {
Done

2018-02-01 18:19 UTC, alex-schell commented on js/infinite/views/products/product-view.js
Done

2018-02-01 18:19 UTC, alex-schell commented on js/infinite/views/products/product-view.js
> +            tmpExternalTrackingURL = tmpExternalTrackingURL.substr(0, tmpLinkPosition) + tmpSlicedString + tmpExternalTrackingURL.substr(tmpLinkPosition)
Done

2018-02-02 12:57 UTC, saviomuc requested changes
Overall looks great. Good work! 2 nitpicks

2018-02-02 12:57 UTC, saviomuc commented on js/infinite/views/products/product-view.js
> +              productTitle = productTitle.replace(/[\/. ,:-]+/g, "_").toLowerCase().slice(0, Math.min(10, productTitle.length));
Reassigning variables is basically mutation and not good practice. For readability just try to break down to something like:

```
    productTitle = this.model
                .get('title')
                .replace(/[\/. ,:-]+/g, "_")
                .toLowerCase()
                .slice(
                  0,
                  Math.min(10, this.model.get('title').length)
                );
```

2018-02-02 12:57 UTC, saviomuc commented on js/infinite/views/products/product-view.js
> +            console.log(externalTrackingURL);
Please remove console.log

2018-02-02 13:07 UTC, saviomuc approved these changes
LGTM 🍦 🎉

2018-02-02 13:58 UTC, merged